# Generated by Django 4.1.1 on 2022-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ManyToManyField(to='main.group'),
        ),
    ]
